apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgvector-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./pgvector-on-nkp-with-cnpg/charts/pgvector-demo
      sourceRef:
        kind: GitRepository
        name: pgvector-on-nkp-with-cnpg
      interval: 5m
  values:
    name: pgvector-demo
    instances: 1
    storageSize: 10Gi
