---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress-gatewayapi
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/gateway_api/wordpress
  prune: true
  sourceRef:
    kind: GitRepository
    name: technote-repo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings # Injects wordpress.gslb.thencpnutanix.com

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress-gslb
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/gslb/wordpress
  prune: true
  sourceRef:
    kind: GitRepository
    name: technote-repo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress-app
  namespace: flux-system
spec:
  dependsOn:
    - name: wordpress-gatewayapi
    - name: wordpress-gslb
  interval: 10m
  retryInterval: 1m
  path: ./applications/wordpress/overlays
  prune: true
  sourceRef:
    kind: GitRepository
    name: technote-repo



# After failover, before bringing up the WordPress app in the primary cluster, patch the Kustomization on primary to 0 replicas.

---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: wordpress-stack
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: ./apps/wordpress/base
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   patches:
#     - patch: |
#         apiVersion: apps/v1
#         kind: Deployment
#         metadata:
#           name: wordpress
#           namespace: wordpress
#         spec:
#           replicas: 0



# After failover, before bringing up the WordPress app in the primary cluster, patch the Kustomization on primary to 0 replicas.

---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: wordpress-stack
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: ./apps/wordpress/base
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   patches:
#     - patch: |
#         apiVersion: apps/v1
#         kind: Deployment
#         metadata:
#           name: wordpress
#           namespace: wordpress
#         spec:
#           replicas: 0