apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  WP_HOSTNAME: "wordpress.gslb.thencpnutanix.com"
  BOUTIQUE_HOSTNAME: "boutique.gslb.thencpnutanix.com"