---
apiVersion: k8gb.io/v1beta1
kind: Gslb
metadata:
  name: wordpress-gslb
  namespace: wordpress
spec:
  resourceRef:
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    name: wordpress-route # Pointing to the new Route
  strategy:
    dnsTtlSeconds: 60
    primaryGeoTag: k8s-primary
    type: failover